### ISSUE TITLE
Faltando requirement.txt e Bug com download

### ISSUE THREAD

**Issue by Saaanzio** [KaylerMm/Python-YouTubeDownloader-TK#1]
Bom dia KaylerMm, acabei encontrando bugs no seu código, alias parabéns pelo lindo aplicativo. Acredito que o senhor esqueceu do requirements.txt e os downloads não estão terminando, ambientes utilizados: pycharm e vscode. Tenha uma ótima terça-feira.

**Comment by KaylerMm** [comment]
Boa tarde. Muito agradecido pela contribuição! O arquivo de requirements.txt foi adicionado. Detalhes da execução estão descritos no README.md
Sobre os bugs encontrados, por favor, forneça mais detalhes sobre seu ambiente, mensagens de erro e códigos exibidos no terminal.
Feliz em ter sua contribuição!
Abs,
Kayler Moura
